### ISSUE TITLE
change_torrent

### ISSUE THREAD

**Issue by daomengRen** [Trim21/transmission-rpc#139]
`client.change_torrent(torrent.id, location=new_path)`

hi, does this move the save location of the torrent, i tried and it failed,I don't know how to solve it, looking forward to your reply, thank you

## Environment

tr version:3.0
RPC:16

**Comment by Trim21** [comment]
try https://transmission-rpc.readthedocs.io/en/v3.3.0/client.html#transmission_rpc.client.Client.move_torrent_data

**Comment by daomengRen** [comment]
Thank you, maybe my needs are special, because I replaced a new machine, so I want to restore all the state before tr, I have backed up the resume and torrent files, but since the save address has changed, I have to change the address.Now it's even worse. When I restart transmission, some torrent addresses have become the default download addresses. I may have to update the save address of each torrent by modifying the resume file, because the original address is / A/B, the new address needs to be changed to /C/B, do you know which way to open the resume file to meet my needs, thanks
