### ISSUE TITLE
get_torrents() ignores arguments.

### ISSUE THREAD

**Issue by varoOP** [Trim21/transmission-rpc#148]
# Description

No arguments other than 'name' are being returned when using get_torrent() or get_torrents().

## Environment

- language version: Python 3.7.3
- app/lib/repo version: Transmission 3.00 (bb6b5a062e)

## How to reproduce

```
>>> import transmission_rpc
>>> client = transmission_rpc.Client()
>>> client.get_torrents(arguments={'trackers', 'name', 'hashString'})
[<Torrent 1 "ubuntu-21.10-desktop-amd64.iso">]
>>> 
```

## Expectations
Expected it to retuirn hashString and trackers of the torrent as well in the output.

## Actual result

The actual result is that it only return the id and the name.

**Comment by Trim21** [comment]
And I'm using python3.8 with transmission 3.0.0, I think the python version doesn't matter.

**Comment by Trim21** [comment]
Are you expecting all properties to be printed when printing `Torrent` object?

**Comment by varoOP** [comment]
Yes, and I have just realized that is where I am wrong. I'll close this up, thanks for the help!
