### ISSUE TITLE
Transmissions crashes when using transmission-rpc

### ISSUE THREAD

**Issue by DeWolfRobin** [Trim21/transmission-rpc#154]
# Description

I have a flask API that in turn makes requests to the transmission instance I have. However, whenever I make a request to the flask API, transmission starts hanging, probably because the RPC client isn't closing the connections.

## Environment

- language version: python 3.9
- app/lib/repo version: latest

## How to reproduce

```
from transmission_rpc import Client, Response
from flask import Flask
import json

app = Flask(__name__)

@app.route('/movies', methods=['GET'])
def getMovieList():
    transmissionRPC = Client(host="example.com", port=9091, username='test', password='test')
    out = []
    for t in transmissionRPC.get_torrents():
        out.append({
        "name": t.name,
        "status": t.status,
        "rate": str(t.rateDownload/1000/1000)+" MB/s",
        "progress": str(t.progress) + "%",
        "eta": t.format_eta()
        })
    return Response(json.dumps(out), mimetype='application/json')

if __name__ == '__main__':
    app.run(host="0.0.0.0", port=5000)
```

## Expectations
Normal JSON return on API request.

## Actual result
Timeouts from Transmission

**Comment by Trim21** [comment]
you should keep a client and use it in every requests, don't create a client for every request
