### ISSUE TITLE
Feature request: add tracker(s) information to Torrent

### ISSUE THREAD

**Issue by jesusrop** [trim21/transmission-rpc#181]
# Description

Feature request: add tracker name to torrent attributes.

## Environment

- python 3.9.2 (debian)
- transmission-rpc 3.3.2 (installed from pip3)

## How to reproduce

Torrent.trackers

## Expectations
Get the name of tracker(s) this torrent belongs to

## Actual result
Information is not available

It would be very helpful to me to know which tracker each torrent belongs to.
In any case, great module. Thank you very much for it!

**Comment by trim21** [comment]
there is trackers on torrent object, it just didn't get typed with properly.

**Comment by trim21** [comment]
```python
import dataclasses

from transmission_rpc import Client

client = Client(...)

torrent = client.get_torrent(...)


@dataclasses.dataclass
class Tracker:
    id: int
    announce: str
    scrape: str
    tier: int


for tracker in torrent.trackers:
    t = Tracker(**tracker)
    print(t)

```
