### ISSUE TITLE
Can't delete file from disc

### ISSUE THREAD

**Issue by nicolasbisi** [trim21/transmission-rpc#182]
# Description

I have a script that is called to remove the downloaded torrent after a while, but even though I set the flag to delete the file as well, it doesn't happen.
If I manually "Trash data and remove from list" from Transmission web UI, it removes from Transmission and deletes the file from the disc as expected.
When I run "client.remove_torrent(torrent.id, delete_data=True)" it only removes the file from Transmission.
## Environment

- language version: Python 3.10.4
- app/lib/repo version: transmission-rpc 3.3.2
- Transmission 3.00

## How to reproduce

client.remove_torrent(1, delete_data=True)
## Expectations
Remove the torrent from Transmission and delete it from the disc.

## Actual result
Only removes the file from Transmission.

**Comment by trim21** [comment]
I can't re-produce this, it works fine on my test.

**Comment by nicolasbisi** [comment]
Hi @trim21, thanks for trying it out.
Is there anything I can do to get more information to track down the problem?

This is the minimum code I used to run it, and it still happens.
`#!/usr/bin/env python3
from transmission_rpc import Client

client = Client(username='USER', password='PASS', port=8000)
client.remove_torrent(31, delete_data=True)`

It's running on a Ubuntu 22.04 LTS machine.
I can run the script and watch the torrent disappear from Transmission web UI, but the file is untouched.

**Comment by trim21** [comment]
> Hi @trim21, thanks for trying it out. Is there anything I can do to get more information to track down the problem?
> 
> This is the minimum code I used to run it, and it still happens. `#!/usr/bin/env python3 from transmission_rpc import Client
> 
> client = Client(username='USER', password='PASS', port=8000) client.remove_torrent(31, delete_data=True)`
> 
> It's running on a Ubuntu 22.04 LTS machine. I can run the script and watch the torrent disappear from Transmission web UI, but the file is untouched.

you can try to set logger to debug level, raw request will be logged.

**Comment by nicolasbisi** [comment]
Ah, thanks. I didn't realise there was an arg for log.

I tried to paste the output here but it was messing up with the formatting.
I've pasted it here:
https://controlc.com/9e39856d6

In the end, it's always a success, but there is this error 409.

I tried again with the same ID (it was already removed) and got exactly the same thing for the last part ('method': 'torrent-remove')

**Comment by trim21** [comment]
first 409 error is expected

**Comment by nicolasbisi** [comment]
So it always succeeds, even when the id doesn't exist?
Is that a transmission problem?

**Comment by trim21** [comment]
I'm getting confusing now, is this issue about removing and existing torrent or non-existing torrent?

**Comment by nicolasbisi** [comment]
The issue is about removing the existing one, but the log I get from the existing and non-existing ones are exactly the same.

**Comment by trim21** [comment]
In that case I think it's something going wrong with transmission itself... Would you mind comparing the requests between web ui and this lib?

**Comment by nicolasbisi** [comment]
Sure. I'm just not sure how to do it.

**Comment by trim21** [comment]
No need to do that, thank you, I can do it myself, I'll try to find what's wrong.

**Comment by nicolasbisi** [comment]
Ok. Thanks.
Let me know if there is anything I can do to help.

**Comment by nicolasbisi** [comment]
Just had a go. No change. The log looks the same as well.

**Comment by trim21** [comment]
this is strange…

**Comment by trim21** [comment]
I don't have idea how to re-produce or fix it now, I'll keep this issue open if someone encoutner this.

**Comment by nicolasbisi** [comment]
Ok. Thanks for trying. Let me know if you think of anything else I can do to help out.

**Comment by garnajee** [comment]
Sorry to reopen this, but it seems that I have the same issue with the lib (latest version transmission-rpc==7.0.5).

By trying to delete a torrent (the file itself and the data) using the `remove_torrent()` function, only the file (`<hash>.torrent` in the transmission folder) is removed. It doesn't matter whether `delete_data` is set to `True` or `False`, the torrent file is always removed. But never the contents of the torrent.

Here is the json data request using the web-ui (with the webui it works fine) : 
```
json_data = '{"arguments":{"delete-local-data":true,"ids":[151]},"method":"torrent-remove"}'
```

Here is my python script : `client.remove_torrent(151,True)`

I don't know what else I can provide, I don't have any other logs.

Thanks
