### ISSUE TITLE
No access for upload / download attributes

### ISSUE THREAD

**Issue by tobiasredel** [trim21/transmission-rpc#193]
# Description

Sometimes its required to calculate custom ratios, etc. For that i would need to read the current upload and download in bytes but i cant see attributes for that from the torrent object. Is there a way to read those attributes?

**Comment by tobiasredel** [comment]
Is there some public documentation of all properties available?

From: Trim21 ***@***.***>
Date: Thursday, 27. October 2022 at 00:14
To: trim21/transmission-rpc ***@***.***>
Cc: Tobias Redel ***@***.***>, Author ***@***.***>
Subject: Re: [trim21/transmission-rpc] No access for upload / download attributes (Issue #193)

I didn't add a helper property for them, just read attribute directly, __getattr__ will handle them.

**Comment by trim21** [comment]
no, you will need to find them in transmission's official RPC document
