### ISSUE TITLE
[Feature Request] Set priority and selected of File in torrent

### ISSUE THREAD

**Issue by ExceptionalError** [trim21/transmission-rpc#194]
Currently it's possible to get the [File infos](https://github.com/trim21/transmission-rpc/blob/317414012e69edac757b56f0e5ef1518cbbe7f78/transmission_rpc/lib_types.py#L10).
I'd like to be able to select and of modify the priority programmatically, e.g.
```
torrent.update_file(name, priority=None, selected=None)
```

**Comment by trim21** [comment]
```py
client.change_torrent(t.hashString, priority_low=[i for i, x in enumerate(t.files()) if x.name.endswith(".txt")])
```

**Comment by ExceptionalError** [comment]
Thank you for the quick reply and sorry I missed it! I looked at the docs for the torrent instead of the client.
A convenience method on the torrent that warps the client call would be nice since it's not clear that this operation is on the client.
e.g. why is `move_data` a torrent method but changing the files a client method that takes the torrent hash.

**Comment by trim21** [comment]
There used to be setter on torrent object to call `client.change_torrent`, but when adding new arguments of new transmission, I think its better to keep all rpc method in one place for maintenance

**Comment by ExceptionalError** [comment]
Sounds reasonable. But I meant a method to just change the files.
Something like this:

```python
torrent.change_file_properties(name, priority_low: Optional[List[str]], unwanted: Optional[List[str]], )
```

**Comment by trim21** [comment]
I mean methods that call client have been removed from torrent object…

**Comment by ExceptionalError** [comment]
Just a hint - maybe add an explicit `id` field to the file object which contains the position?
I tried disabling through the file name because I overlooked the `enumerate` in your example and from the docstring it's not clear what the file id is.

**Comment by trim21** [comment]
Yes I just add them when writing [the snippet](https://github.com/trim21/transmission-rpc/issues/194#issuecomment-1296108257)
