### ISSUE TITLE
Can't rename the file name in the torrent

### ISSUE THREAD

**Issue by CakesTwix** [trim21/transmission-rpc#216]
# Description

I write a simple script in python in which I specify the name of the torrent and a template for the new file name

## Environment

- language version: Python 3.10.8
- app/lib/repo version: transmission-rpc==3.4.0

## How to reproduce

```
from transmission_rpc import Client
from transmission_rpc.utils import format_size
from transmission_rpc.error import TransmissionConnectError
import argparse

config = {"username": "TEST",
          "password": "TEST",
          "port": 443,
          "host": "example.com",
          "protocol": "https",
          "rpc": "rpc"
        }

# Instantiate the parser
parser = argparse.ArgumentParser(description='Massive rename torrent files in torrent, lol')

# Required positional argument
parser.add_argument('name', type=str, help='Name of torrent')
parser.add_argument('template', type=str, help='Name of torrent')
args = parser.parse_args()

try:
    TransmissionClient = Client(host=config["host"], 
        port=config["port"], 
        username=config["username"], 
        password=config["password"],
        path=config["rpc"],
        protocol=config["protocol"]
    )
except TransmissionConnectError:
    print("No connection")
    exit()

for torrent in TransmissionClient.get_torrents():
    if args.name in torrent.name:
        new_files = {torrent.id: {}}
        i = 1
        for name_id, name in enumerate(torrent.files()):
            new_name = args.template.format(i)
            print(name)
            new_files[torrent.id].update({name_id: {"name": f"{torrent.name}/{new_name}", "selected": True}})
            i += 1
print(new_files)
TransmissionClient.set_files(new_files)
```
python /home/cakestwix/transmission_rename.py Bocc "Episode S01E{}.mkv"

## Expectations

Episode S01E1.mkv
Episode S01E2.mkv
Episode S01E3.mkv
Episode S01E4.mkv
Episode S01E5.mkv
Episode S01E6.mkv
Episode S01E7.mkv
Episode S01E8.mkv
Episode S01E9.mkv

## Actual result

![image](https://user-images.githubusercontent.com/57946485/208312291-c9d922a0-a411-4ca9-b907-33534178a680.png)

**Comment by trim21** [comment]
Is it possible to set torrent file to another name in transmission? I never done that...

**Comment by CakesTwix** [comment]
Possible. Tremotesf client. I asked the developer to implement the mass renaming feature. I decided to write a script for this
![image](https://user-images.githubusercontent.com/57946485/208312583-d09b97d7-76d3-4e08-9e8c-5837441817b9.png)

**Comment by trim21** [comment]
And this episode 01 will download to `Episode S01E01.mkv` file on disk? or it's renamed by Tremotesf ?

**Comment by CakesTwix** [comment]
Just renamed to new name. I need this for a normal series number parser in Jellyfin

**Comment by trim21** [comment]
can you tell my which rpc it's using? I didn't find it in transmission's document https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md

**Comment by CakesTwix** [comment]
I don't know how to check, but as I understand it, it uses its own library https://github.com/equeim/libtremotesf

**Comment by trim21** [comment]
looks like it's `torrent-rename-path`, you can just call it directly.

and `set_files` has been removed in v4

**Comment by trim21** [comment]
it's `Client(...).rename_torrent_path`

**Comment by CakesTwix** [comment]
Thanks, works!

```
for torrent in TransmissionClient.get_torrents():
    if args.name in torrent.name:
        i = 1
        for name_id, name in enumerate(torrent.files()):
            new_name = args.template.format(i)
            TransmissionClient.rename_torrent_path(torrent.id, name.name, new_name)
            i += 1
```
