### ISSUE TITLE
File transfer is really slow

### ISSUE THREAD

**Issue by himabindugit** [trim21/transmission-rpc#219]
# Description

In summary, we are transferring data from EC2 instance to an on-premises system. The data is compressed in a tarball and then broken into smaller chunks to be transferred via BitTorrent client. We can successfully transfer a 6.31 GB file this way within 40 minutes (~24Mb/s at 35min), but with a different file of equal size, this transfer is stalling (stuck for more than an hour after only 773kb transferred). We tried benchmark the data transfer speed from an Ec2 instance to the server manually with out Bittorrent. When we send data from the EC2 instance to the server we are getting a transfer rate of 29.7 Mbits/sec which is a lot faster.  This rules out any issues with the network.  Next, we are trying to find out if we can determine what the cause of the slow transfer is.

## Environment

- language version: Python
- app/lib/repo version:
- transmissionrpc==0.11

## Expectations
File upload/transfer should be normal.

## Actual result
File transfer rate is really slow.

**Comment by trim21** [comment]
This library is only a python wrapper on transmission's RPC protocol, it doesn't handle downloading. You should create issue at transmission's repo.
