### ISSUE TITLE
list current torrent peer

### ISSUE THREAD

**Issue by q1208c** [trim21/transmission-rpc#229]
Hi, I am new user for transmission rpc.
I want to list all peers connected to me.
but, I only got the count, not the list.
I think I use the wrong function (Torrent.peers), which one is the right one ?
thanks.

**Comment by trim21** [comment]
I think you are using right property, but I make a mistake, it doesn't return `int`, it return a list instead.

https://github.com/trim21/transmission-rpc/blob/v4.0.0-alpha.5/transmission_rpc/torrent.py#L482

**Comment by q1208c** [comment]
Currently, the stable version (come with pip install) is 3.4.0, the Torrent.peers is available in 4.0, so, I just read the document from 4.0, not really use. 
thanks for explain.

**Comment by trim21** [comment]
> Currently, the stable version (come with pip install) is 3.4.0, the Torrent.peers is available in 4.0, so, I just read the document from 4.0, not really use. thanks for explain.

It's available in 3.4.0 just not documented and typed

**Comment by q1208c** [comment]
> 

Thank you for your info. 
I got it.
