### ISSUE TITLE
Is this library thread safe?

### ISSUE THREAD

**Issue by Vovcharaa** [trim21/transmission-rpc#239]
I want to use this library in async application with `asyncio.to_thread`.
Is `Client` safe to use in threadpool?

**Comment by trim21** [comment]
No it doesn't, you will need to create a client for each thread or add a lock

**Comment by trim21** [comment]
If you want to use it in asynchronous application I suggest you add a lock on all rpc methods call.

**Comment by Vovcharaa** [comment]
> If you want to use it in asynchronous application I suggest you add a lock on all rpc methods call.

Defeats the whole point of going async.

I guess, I need to create some `Client` pool for using with threads then.
Thanks for the answer.

**Comment by trim21** [comment]
just out of curious, why youe need to use transmission rpc concurrently…

**Comment by Vovcharaa** [comment]
@trim21 I am rewriting my [transmission telegram bot](https://github.com/Vovcharaa/transmission-telegram-bot) with new version of [python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot) which went async in last major version. And also I want to implement some notifications for download statuses, which requires some backgroud job.
Seems like I will create 2 client instances for main and backgroud threads. I can go with blocking calls for rpc because bot is used by 3-4 people at most, so it's not a big deal.
