### ISSUE TITLE
Need help building from source

### ISSUE THREAD

**Issue by st3iny** [trim21/transmission-rpc#242]
# Description

I'm trying to package this library for the [AUR](https://aur.archlinux.org/packages/python-transmissionrpc) but the built wheel does not contain the code (only dist-info metadata). It worked before when using `setup.py` and I'm trying to adapt the package for use with `pyproject.toml`.

```
[builder@95bfb9f47da8 transmission_rpc-4.1.2]$ poetry build --format wheel
Building transmission-rpc (4.1.2)
  - Building wheel
  - Built transmission_rpc-4.1.2-py3-none-any.whl
[builder@95bfb9f47da8 transmission_rpc-4.1.2]$ unzip dist/transmission_rpc-4.1.2-py3-none-any.whl
Archive:  dist/transmission_rpc-4.1.2-py3-none-any.whl
  inflating: transmission_rpc-4.1.2.dist-info/LICENSE
  inflating: transmission_rpc-4.1.2.dist-info/METADATA
  inflating: transmission_rpc-4.1.2.dist-info/WHEEL
  inflating: transmission_rpc-4.1.2.dist-info/RECORD
```

I also tried building via PEP 517 (`python -m build --wheel --no-isolation`) with the same result. It builds fine but the resulting wheel is not containing the actual code.

Do you know what I'm doing wrong here? Any help is highly appreciated.

## Environment

- language version: Python 3.10.9
- app/lib/repo version: 4.1.2 from https://files.pythonhosted.org/packages/9c/5e/a99af816aa613a55f5b473f21267fdec76dc10ebc040bd5ff407b0fa5823/transmission_rpc-4.1.2.tar.gz

## How to reproduce

1. Download the source tar from the above link
2. Extract it and change to the contained directory.
3. Run `poetry build --format=wheel`.

## Expectations

Poetry should build a wheel that contains the code of this library.

## Actual result

The built wheel does not contain any code. It only contains dist-info metadata.

**Comment by trim21** [comment]
Why don't you just download wheel from github release

**Comment by trim21** [comment]
I know nothing about aur so I don't understand what you actually want...

If you are trying to build pip wheel you can just clone the repo and run poetry build, that's all I need and that's what ci do.

**Comment by trim21** [comment]
https://github.com/trim21/transmission-rpc/blob/52b5528b3db7429cc007061facfa8525a7e3c9c3/.github/workflows/ci.yaml#LL43C8-L43C8
