### ISSUE TITLE
Feature Request: also raise http_data when raise TransmissionError

### ISSUE THREAD

**Issue by liyihc** [trim21/transmission-rpc#262]
# Description

I want to get torrent id for a url and use Client.add_torrent method. It worked with transmission version<4 but raise a TransmissionError with message "duplicate torrent" when transmission version>4

![fig1](https://user-images.githubusercontent.com/39760662/230761666-38348fdb-c7d8-4333-aca5-4c2cba6027aa.png)

## Environment

transmission: 4.0.2
transmission-rpc: 4.1.5

## How to reproduce

add a existing torrent url using Client.add_torrent method.

## Expectations

I hope to change [this line](https://github.com/trim21/transmission-rpc/blob/34607a76a88438d81c5aaea83057e020d3986f26/transmission_rpc/client.py#L239) from `raise TransmissionError(f'Query failed with result "{data["result"]}".')` to `error = TransmissionError(f'Query failed with result "{data["result"]}".') ; error.args = (*error.args, data) ; raise error`. Then I could retrive torrent id from exception like this figure
![fig2](https://user-images.githubusercontent.com/39760662/230761856-53b2b7da-7b92-4e6e-8d04-2d2c8139f015.png)

**Comment by trim21** [comment]
good idea,I will add more details in error
