### ISSUE TITLE
How to logout from transmission-rpc ?

### ISSUE THREAD

**Issue by matthoug** [trim21/transmission-rpc#269]
Hello,

I'm looking for a way to logout from transmission after performing somes tasks, but i can't find anything on readthedoc, is there any way to disconnect ?

I'm able to connect :

c = Client(host="localhost", port=9091)

But the session stays up while the script is running.

Regards,

**Comment by trim21** [comment]
just create a new client, there is no way to "logout"

**Comment by trim21** [comment]
transmission-daemon use a semi-stateless auth flow, rpc clients don't need to create a session and them also can't revoke a session. So there it no way to logout.

It you just want to close the connection just use client as context manager.

**Comment by trim21** [comment]
I'll close this issue for now, feel free to append more questions/suggestions
