### ISSUE TITLE
Name doesn't get populated

### ISSUE THREAD

**Issue by cicuz** [Trim21/transmission-rpc#29]
# Description

I'm not getting the field `name` populated in the returned `Torrent` object from either `get_torrent` or `get_torrents`; I managed to get it by digging in the private methods like so:

```
>>> query = json.dumps({'tag': 123, 'method': 'torrent-get', 'arguments': {'fields': ["id", "name"], 'ids': [52]}})
>>> c._http_query(query)
'{"arguments":{"torrents":[{"id":52,"name":"theTorrentName"}]},"result":"success","tag":123}\n'
```

but for some reason it doesn't seem to make it all the way through to the `Torrent` object.

Ok scratch that, I think I found the issue: the `Torrent` `__init__` method has the signature `(self, client, fields)`, but the call from `_request` doesn't seem to be passing the `client`, so the `fields` probably get garbled. I don't have time to dig more right now, but I'll be back later :)

cheers!

## Environment

- language version: python 3.7
- app/lib/repo version: 3.0.0a

**Comment by Trim21** [comment]
I'm not sure the contractor of `Torrnet` is the problem.`self` in Client methods means client itself.

I'll try to find the reason here later.

**Comment by cicuz** [comment]
You're right, it actually works fine, I was sloppy in my investigations.

Still, `t.name` outputs correctly, but `f"{t}"` or `str(t)` do not and they just print `Torrent`, so I guess the issue I'm having is with the `_get_name_string` method rather

**Comment by cicuz** [comment]
ok this time I got it for real :)

```
>>> t._get_name_string()
b'aTorrentName'
>>> isinstance(_, str)
False
```

cfr. the `__str__` method:

```
def __str__(self):
        name = self._get_name_string()
        if isinstance(name, str):
            return 'Torrent \"%s\"' % (name)
        else:
            return 'Torrent'
```

**Comment by Trim21** [comment]
@cicuz I found that I have fixed this issue, but I didin't release it yes... Upgrade to 3.0.0a4 please
