### ISSUE TITLE
Transmission 3.0

### ISSUE THREAD

**Issue by biloucat** [Trim21/transmission-rpc#32]
# Description

transmission-rpc does not take into account Transmission 3.0

## How to reproduce

from transmission_rpc import Client
from transmission_rpc import Torrent
torrent_hash='xxxxxxxxxxxxxxxxxxxx'
c = Client(username='myusername', password='mypassword')
print(c.rpc_version)# **for me --> 16**
torrent=c.get_torrent(torrent_hash)
print(torrent.labels)  #**--> builtins.AttributeError:No attribute labels**

**Comment by Trim21** [comment]
Is there a field named `labels' in `torrent._fields`?

**Comment by Trim21** [comment]
O sorry, I didn't realized transmission 3.0 is released. I'll make a update for it.

**Comment by Trim21** [comment]
Is there a labels field in `torrent._fields`?

**Comment by biloucat** [comment]
No there is not.

**Comment by Trim21** [comment]
should be fixed by version 3.1.0

**Comment by biloucat** [comment]
I just tested: it works.
Thank you for your speed !
