### ISSUE TITLE
Delete the torrent file question

### ISSUE THREAD

**Issue by romanoh** [trim21/transmission-rpc#329]
# Description

first i am a newbie at python, so i am sorry if its been asked, after the process i cant delete the torrent file(or move it), even if it is not an transmission-rpc problem, i thought to ask here.

## Environment
transmission-rpc   3.4.0

## How to reproduce

https://pastebin.com/QmrS38GS

## Expectations

file deleted

## Actual result
"Exception has occurred: PermissionError [WinError 32] The process cannot access the file because it is being used by another process"

**Comment by trim21** [comment]
if it is not an transmission-rpc problem, do not ask it here.
