### ISSUE TITLE
"removed" field is discarded on torrent-get call with "recently-active" for ids

### ISSUE THREAD

**Issue by g-regor** [trim21/transmission-rpc#48]
Calling `get_torrents` with `"recently-active"` as ids, only a list of torrents is returned and not the array of removed torrent ids.

From the [RPC API spec](https://github.com/transmission/transmission/blob/3.00/extras/rpc-spec.txt#L170-L172)

> If the request's "ids" field was "recently-active", a "removed" array of torrent-id numbers of recently-removed torrents.

The code is acknowledging `"recently-active"` as a valid value for ids, but the returned `"removed"` field is ignored.

I think that there should be a method specifically for this kind of rpc call.

**Comment by Trim21** [comment]
Considering a way to add this feature but not breaking current code...
