### ISSUE TITLE
`Torrent.pieces` is not user-friendly

### ISSUE THREAD

**Issue by dechamps** [trim21/transmission-rpc#484]
Currently, the `Torrent.pieces` field is the same as the `pieces` field in the Transmission RPC response, that is:

> A bitfield holding pieceCount flags which are set to 'true' if we have the piece matching that position. JSON doesn't allow raw binary data, so this is a base64-encoded string.

While this makes sense for JSON, Python can do better. `transmission-rpc` could at least base64-decode the field to binary, or even better, could expose it as a list of bools.

**Comment by trim21** [comment]
we can make it bitmap in next major version

**Comment by trim21** [comment]
if I can finish this before tr 4.1.0 is released
