### ISSUE TITLE
Make datetime values timezone-aware

### ISSUE THREAD

**Issue by jwodder** [Trim21/transmission-rpc#93]
Currently, the library converts timestamps to `datetime` objects by just calling `datetime.datetime.fromtimestamp(timestamp)`.  Although the resulting objects are in the system timezone, that information is not properly provided, as the datetimes are [naïve rather than aware](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects).  The `datetime` instances would be more usable if they had timezone information attached, either the system timezone (by doing `datetime.datetime.fromtimestamp(timestamp).astimezone()`) or by using UTC (by doing `datetime.datetime.fromtimestamp(timestamp, tz=datetime.timezone.utc)`).

**Comment by Trim21** [comment]
I may need some more information about this, could you get me some examples about how to make it 'more usable'?

**Comment by jwodder** [comment]
@Trim21 All I'm asking is to basically change this line:

https://github.com/Trim21/transmission-rpc/blob/1c1e05c9a3d1e4a35ff87a50ec985012af586b22/transmission_rpc/torrent.py#L316

to:

```python
return datetime.datetime.fromtimestamp(self._fields["activityDate"].value).astimezone()
```

and likewise for the other `fromtimestamp()` calls.  This produces a `datetime` in the system timezone with information about that timezone stored in the `tzinfo` attribute.  This lets the user be confident in manipulating, storing, transmitting, etc. the `datetime`, as it will contain enough information to identify a specific second in history.  Without timezone information, you just see something like "2021-06-24 22:19:02", which is so ambiguous that it could be any second in a range of more than(!) 24 hours.
